version: '2'

services:
  concourse-db:
    image: postgres:9.5
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /database

  concourse-web:
    image: concourse/concourse
    depends_on:
      - concourse-db
    command: web
    ports:
      - "8080:8080"
    volumes:
      - "./keys/web:/concourse-keys"
    environment:
      CONCOURSE_BASIC_AUTH_USERNAME: ${CONCOURSE_BASIC_AUTH_USERNAME}
      CONCOURSE_BASIC_AUTH_PASSWORD: ${CONCOURSE_BASIC_AUTH_PASSWORD}
      CONCOURSE_EXTERNAL_URL: "${WEB_TUNNEL_URL}"
      CONCOURSE_POSTGRES_DATA_SOURCE: |-
        postgres://concourse:changeme@concourse-db:5432/concourse?sslmode=disable

  concourse-worker:
    image: concourse/concourse
    privileged: true
    depends_on:
      - concourse-web
    command: worker
    volumes:
      - "./keys/worker:/concourse-keys"
    environment:
      CONCOURSE_TSA_HOST: concourse-web
